[PREP]
tri_exe = 'bin/triangle.exe'
tri_working = 'triangle/wdr_temp'
gdalwarp_exe = 'bin/gdalwarp.exe'
default_statvars = 'static/prms_control_templates/statvar_defaults.toml'
control_defaults = 'static/prms_control_templates/base_defaults.toml'
default_basinvars = 'static/prms_control_templates/basin_out_defaults.toml'
default_hruvars = 'static/prms_control_templates/hru_out_defaults.toml'
default_subvars = 'static/prms_control_templates/subbasin_out_defaults.toml'
default_segvars = 'static/prms_control_templates/segment_out_defaults.toml'
raster_remaps = 'static/raster_remaps/landfire/post_2016'
snarea_curves.western = [0.05, 0.24, 0.4, 0.53, 0.65, 0.75, 0.82, 0.88, 0.93, 0.99, 1.0]
tstorm.western = [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0]