charset-normalizer=3.2.0
cligj=0.7.2
contourpy=1.1.0
cycler=0.11.0
dataretrieval=1.0.5
Fiona=1.9.4.post1
flopy=3.4.2
fonttools=4.42.1
GDAL=3.0.2
idna=3.4
importlib-metadata=6.8.0
importlib-resources=6.0.1
kiwisolver=1.4.5
matplotlib=3.7.2
mkl-fft=1.3.6
mkl-service=2.4.0
packaging=23.1
pandas=2.1.0
Pillow=10.0.0
PyCRS=1.0.2
pygsflow=1.1.0
pyproj=3.6.0
pyshp=2.3.1
python-dateutil=2.8.2
pytz=2023.3.post1
requests=2.31.0
richdem=0.3.4
Rtree=1.0.1
shapely=2.0.1
six=1.16.0
tzdata=2023.3
urllib3=2.0.4
xarray=2023.8.0
zipp=3.16.2
