import os
from .domain import *
from .params import *

NOT_NEEDED_XYZ = ['subbasin_down',
                  'soil_moist_init',
                  'soil_rechr_max',
                  'soil_rechr_init',
                  'tmax_allrain',
                  'basin_tsta',
                  'gvr_cell_pct',
                  'gvr_hru_pct',
                  'hru_psta',
                  'hru_tsta',
                  'max_missing',
                  'rain_adj',
                  'snow_adj',
                  'soil_moist_init_frac',
                  'soil_rechr_init_frac',
                  'soil_rechr_max_frac',
                  'sstor_init',
                  'sstor_init_frac',
                  'tmax_index',
                  'tmax_lapse',
                  'tmin_lapse',
                  'hru_subbasin',
                  'gw_up_id',
                  'gw_down_id',
                  'gw_strmseg_down_id',
                  'gw_pct_up',
                  'gvr_cell_id',
                  'gvr_hru_id',
                  'ssr2gw_sq',
                  'tmax_allrain_sta']

